name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        make
    - name: test
      run: |
        cd build
        ctest
